modLoader="javafml" 
loaderVersion="[43,)"
license="All rights reserved"
issueTrackerURL = "https://github.com/${repository}/issues"

[[mods]] 
modId="${mod_id}"
version="${mod_version}" 
 
displayName="${mod_name}"
authors="${mod_author}"
description='''
Use commands to export the IDs of registry entries into JSON files
'''

[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,)"
    ordering="NONE"
    side="BOTH"
