# <meta>
#    <source>@pssbletrngle/github-meta-generator</source>
#    <version>1.0.95</version>
#    <timestamp>2026-06-21T19:16:02.047Z</timestamp>
#    <hash>fe056535c3408758</hash>
# </meta>

neoforge:
  - "/^neoforge$/m"
forge:
  - "/^forge$/m"
fabric:
  - "/^fabric$/m"

1.21.x:
  - "/^1.21$/m"
1.20.x:
  - "/^1.20$/m"
1.19.x:
  - "/^1.19$/m"
