# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Project
mod_id=registry_dump
mod_name=Registry Dump
mod_author=possible_triangle
mod_version=0.0.0-dev
release_type=release
maven_group=com.possible-triangle

# Common
mc_version=1.21.10

forge_version=60.0.10

# Neoforge
neoforge_version=21.10.30-beta

# Fabric
fabric_api_version=0.136.0+1.21.10
fabric_loader_version=0.17.3

# Publishing
repository=pssbletrngle/registrydump
modrinth_project_id=UAzbcRGX