# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Project
mod_id=registry_dump
mod_name=Registry Dump
mod_author=possible_triangle
mod_version=0.0.0-dev
mod_description=Use commands to export the IDs of registry entries into JSON files

# Common
mc_version=1.20.1

# Neoforge
forge_version=47.4.26

# Fabric
fabric_api_version=0.92.12+1.20.1
fabric_loader_version=0.19.5

# Publishing
maven_group=com.possible-triangle
release_type=release
repository=pssbletrngle/registrydump
modrinth_project_id=UAzbcRGX
version_strategy=with_minecraft_version
