modLoader = "javafml"
loaderVersion = "[1,)"
license = "https://github.com/${repository}/blob/HEAD/LICENSE.md"
issueTrackerURL = "https://github.com/${repository}/issues"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
updateJSONURL = "https://api.modrinth.com/updates/registry-dump/forge_updates.json?neoforge=only"
displayName = "${mod_name}"
authors = "${mod_author}"
description = "${mod_description}"

[[dependencies.${mod_id}]]
modId = "neoforge"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
versionRange = "${mc_version_range}"
ordering = "NONE"
side = "BOTH"
